# name: check-graphviz-actions
# Trigger the workflow on [pull_request, push]
# but only for the main branch 
on:
  pull_request: 
  push: 
    branches:
      - master
jobs:
  check-graphviz-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Graphviz 
        uses: ts-graphviz/setup-graphviz@v1
      - name: Create Svg
        run:  |
            dot -Tsvg error-handling.gv > new-error-handling.svg
            cmp -l error-handling.svg new-error-handling.svg
