# name: check-graphviz-actions
# Trigger the workflow on [pull_request, push]
# but only for the main branch 
on: 
  pull_request: 
    branches: [ master ]
  push: 
    branches: [ master]

jobs:
  check-graphviz-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Graphviz 
        uses: ts-graphviz/setup-graphviz@v1
        with:
            graphviz-version: '2.47.3 (20210619.1520)'
      - name: Create Svg
        run:  dot -Tsvg error-handling.gv > new-error-handling.svg
            # cmp -l error-handling.svg new-error-handling.svg
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: new-error-handling.svg
          retention-days: 5